### ISSUE TITLE
Error: project name with hyphen and underscore

### ISSUE THREAD

**Issue by diengiau** [lockedata/pRojects#36]
Hi, thank you for your package. Today I got an error when I tried to create a new package with underscore or hyphen, as below:

``` r
pRojects::createTrainingProject(name = "sample-one", 
dirs = c("data", "handouts", "slides"), 
handoutEngine = "rmarkdown", 
slideEngine = "rmarkdown", 
travis = F, packrat = F, git = F, readme = TRUE)
#> Creating skeleton
#> Error: sample-one is not a valid package name: it should contain only
#> ASCII letters, numbers and dot, have at least two characters
#> and start with a letter and not end in a dot.
```
This code created an empty folder with the name `sample-one`. Do you have any idea? Sometimes, it is inconvenient without the hyphen to name a project. Now my solution is a name without the hyphen first, then rename it later.

**Comment by stephlocke** [comment]
Because we use the R package capability to manage dependencies, the R package naming rules apply. These are: 

- only (ASCII) letters, numbers and dot
- have at least two characters
- start with a letter and not end in a dot

We should probably have some sort of rollback so that it doesn't leave a partial implementation on the file system and some validation on the name to reduce confusion and errors. I'll raise separate tickets for these. I hope the above info helped and if you'd like to work on making it easier for other users we happily accept Pull Requests and offer mentoring through the process if you haven't made changes to an R package on github before.

**Comment by diengiau** [comment]
After reading your answer and *R Package* book again, I understood the error. Because you use the R package to create the new project, I have no idea how to deal with this name rule. Anyway, I think your package approach has some advantages (e.g., dependencies as you mentioned). I will start to use package rather than a folder structure as in `ProjectTemplate`. Thank you for your explanations.

**Comment by stephlocke** [comment]
In terms of a name that satisfies the use of a delimiter between terms and the package rules, you could run `pRojects::createTrainingProject("sample.one")`

In terms of making things more user friendly in the long run, we could cleanse the name so it satisfies folder name conventions and package name conventions in the DESCRIPTION. Do you think them differing would you cause you difficulties?

**Comment by diengiau** [comment]
Yes,  I just want to create a project's name that easy to read. So it's a good idea to use `sample.one` . Thank you for your suggestion.

**Comment by stephlocke** [comment]
Awesome, sorry the error was unclear and we've got stuff on the TODO to try and improve the experience for folks. Please feel free to provide Issues with bugs or feedback and, of course, if you wanna make some changes yourself please feel to tackle an issue and submit a PR. We'll also offer help along the way if you need it.
