### ISSUE TITLE
Improve file path handling

### ISSUE THREAD

**Issue by stephlocke** [lockedata/pRojects#7]
Current iterations of functions assume you want to create a directory below your current one. Modify the functions to allow a path to be provided.

**Comment by jonmcalder** [comment]
I started looking at this last night, but ran into issues with createBasicProject() due to the use of devtools:::use_template() which calls as.package() which calls package_file(), and that expects a DESCRIPTION file (which clearly didn't exist in a new path) as it traverses the directory tree. I was confused for a while and it was late so I didn't get any further :-( Anyway, it looks like you have since fixed that, so I'll try pick this (and other issues) up again later when I have time.

**Comment by stephlocke** [comment]
Yeah, I've found I started making a reasonable amount of variants of devtools functions to tweak to behaviour I prefer / to avoid file opening issues. Ultimately, we may need some sort of standalone dir handling methodology.

**Comment by maelle** [comment]
I'll check overlap with https://fs.r-lib.org/reference/index.html
